authors:
  kevinyamauchi:
    name: Kevin Yamauchi
    description: Scientist and engineer
    avatar: https://github.com/kevinyamauchi/didactic-octo-waddle/blob/main/docs/blog/posts/assets/profile.png?raw=true
